trigger:
- development

pool:
  vmImage: 'ubuntu-latest'

variables:
  WORKSPACE: '$(Build.SourcesDirectory)'

container: 
  image: azurefloripaworkshopacr2024.azurecr.io/azure-floripa-terragrunt:v1 
  endpoint: acrconnector

steps:
- checkout: self
  displayName: 'Checkout the repository'

- script: |
    echo "Workspace: $(WORKSPACE)"
    echo "Azure Container Name: $(AZURE_CONTAINER_NAME)"
    echo "Azure Storage Account Name: $(AZURE_STORAGE_ACCOUNT_NAME)"
    ls -la
  displayName: 'Display Environment Variables'

- script: |
    echo "Changing directory to $(WORKSPACE)"
    cd $(WORKSPACE)
    terragrunt init
  displayName: 'Terragrunt Init'

- script: |
    echo "Changing directory to $(WORKSPACE)"
    cd $(WORKSPACE)
    terragrunt plan
  displayName: 'Terragrunt Plan'

- script: |
    echo "Changing directory to $(WORKSPACE)"
    cd $(WORKSPACE)
    terragrunt apply -auto-approve
  displayName: 'Terragrunt Apply'
