trigger:
- development

pool:
  vmImage: 'ubuntu-latest'

variables:
  WORKSPACE: '$(Build.SourcesDirectory)'

container: 
  image: azurefloripaworkshopacr2024.azurecr.io/azure-floripa-terragrunt:v1 
  endpoint: acrconnector

steps:
- checkout: self
  displayName: 'Checkout the repository'

- script: |
    echo "Changing directory to $(WORKSPACE)"
    terragrunt run-all init
  displayName: 'Terragrunt Init'

- script: |
    echo "Changing directory to $(WORKSPACE)"
    terragrunt run-all plan
  displayName: 'Terragrunt Plan'

- script: |
    echo "Changing directory to $(WORKSPACE)"
    terragrunt run-all --terragrunt-non-interactive apply -auto-approve
  displayName: 'Terragrunt Apply'
