trigger:
- development

pool:
  vmImage: 'ubuntu-latest'

variables:
  WORKSPACE: '$(Build.SourcesDirectory)'

container: 
  image: alpine/terragrunt:latest 

steps:
- checkout: self
  displayName: 'Checkout the repository'

- script: |
    cd $(git diff --name-only HEAD~1 HEAD | while read -r file; do dirname "$file"; done | sort -u) && terragrunt init && terragrunt plan
  displayName: 'Terragrunt Init and Plan'

- script: |
    cd $(git diff --name-only HEAD~1 HEAD | while read -r file; do dirname "$file"; done | sort -u) && terragrunt apply -auto-approve
  displayName: 'Terragrunt Apply'