trigger:
- development

pool:
  vmImage: 'ubuntu-latest'

variables:
  WORKSPACE: '$(Build.SourcesDirectory)'

container: 
  image: azurefloripaworkshopacr2024.azurecr.io/azure-floripa-terragrunt:v1 

steps:
- checkout: self
  displayName: 'Checkout the repository'

- script: |
    bash -c 'terragrunt init && terragrunt plan'
  displayName: 'Terragrunt Init and Plan'

- script: |
    bash -c 'terragrunt apply -auto-approve'
  displayName: 'Terragrunt Apply'